version: '3.0'

services:
  web:
    # Uses Dockerfile
    # build: .

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3001:3001"

    volumes:
      - /app/node_modules
      - .:/app